# Generated by Django 3.0.5 on 2020-06-04 20:02

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('idCard', models.ImageField(null=True, upload_to='idCard')),
                ('regType', models.CharField(choices=[('Self', 'Self'), ('Group', 'Group'), ('Corporate', 'Corporate'), ('Others', 'Others')], max_length=25, null=True)),
                ('ticketNo', models.IntegerField(default=1, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('expDate', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('random', models.IntegerField(null=True)),
            ],
        ),
    ]
